### ISSUE TITLE
ciftisavereset not working when manipulating pconns and saving as pscalars

### ISSUE THREAD

**Issue by bensrivastava** [Washington-University/cifti-matlab#9]
Hi,
 In the newest version of ciftisavereset I am able to open pconns, modify them to pscalar format, and the save as a pscalar file, but there appears to be a glitch. 

`cii=ciftiopen('matrix.pconn.nii',workbench);
cii = 

  struct with fields:

    metadata: [1×4 struct]
     diminfo: {[1×1 struct]  [1×1 struct]}
       cdata: [414×414 single]`

>> new=cii.cdata(:,414);
>> cii.cdata=new;
>> ciftisavereset(cii,'/filepath/new.pscalar.nii',workbench)

 the file won't open in workbench.   Also it cannot be read with wb_command -file-information   On the original version it still works.  
![Screen Shot 2021-12-20 at 1 01 09 PM](https://user-images.githubusercontent.com/42418639/146817817-e1ed722a-39fa-4758-a184-c8de7539485a.png)

**Comment by coalsont** [comment]
The xml code wasn't escaping special characters when writing attributes.  Fixed in commit 37324a98a53eb4ad5e2a3c8725975dce70457de4.
